version: '3.8'

services:
  app:
    container_name: comfy-app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
        - 8080:8080

    environment:
      - FIREBASE_KEY_PATH=/app/firebase-key.json